# Generated by Django 2.2.2 on 2019-06-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190615_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ua', 'Ukrainian'), ('ru', 'Russian')], default='en', help_text='Book language', max_length=15),
        ),
    ]
