# Generated by Django 2.2.2 on 2019-06-15 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20190615_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['book', 'status', 'due_back']},
        ),
    ]
