# Generated by Django 2.2.2 on 2019-06-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20190615_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(default='genre', help_text='Enter a book genre (e.g. Science Fiction)', max_length=200),
            preserve_default=False,
        ),
    ]
