# Generated by Django 2.2.2 on 2019-06-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20190615_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(default='Lorem Ipsum'),
            preserve_default=False,
        ),
    ]
