# Generated by Django 2.2.2 on 2019-06-27 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['book', 'status', 'due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
